FROM maven:amazoncorretto AS build
WORKDIR /app
COPY . .
RUN mvn clean install

FROM artisantek/tomcat:1
COPY --from=build /app/target/*.war /usr/local/tomcat/webapps/
EXPOSE 8080
ENTRYPOINT ["run", "catalina.sh"]
